services:
  dotorganizer:
    image: ironman9967/dot-organizer
    restart: always
    environment:
      PORT: 8080
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: arm64v8/redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 15 1 --loglevel warning
    volumes: 
      - datasource:/data
volumes:
  datasource:
    driver: local
